<?php

namespace ContainerPbWxSbT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_STYWlMkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sTYWlMk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sTYWlMk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'info_pr' => ['privates', '.errored..service_locator.sTYWlMk.App\\Entity\\InfoPratique', NULL, 'Cannot autowire service ".service_locator.sTYWlMk": it references class "App\\Entity\\InfoPratique" but no such service exists.'],
        ], [
            'info_pr' => 'App\\Entity\\InfoPratique',
        ]);
    }
}
