<?php

namespace ContainerPbWxSbT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JycfIJzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jycfIJz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jycfIJz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'saison' => ['privates', '.errored..service_locator.jycfIJz.App\\Entity\\Saison', NULL, 'Cannot autowire service ".service_locator.jycfIJz": it references class "App\\Entity\\Saison" but no such service exists.'],
        ], [
            'saison' => 'App\\Entity\\Saison',
        ]);
    }
}
