<?php

namespace ContainerPbWxSbT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QC_MMsuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QC.MMsu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QC.MMsu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'activiteRepository' => ['privates', 'App\\Repository\\ActiviteRepository', 'getActiviteRepositoryService', true],
            'favorieRepository' => ['privates', 'App\\Repository\\FavorieRepository', 'getFavorieRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'pays' => ['privates', '.errored..service_locator.QC.MMsu.App\\Entity\\Pays', NULL, 'Cannot autowire service ".service_locator.QC.MMsu": it references class "App\\Entity\\Pays" but no such service exists.'],
            'paysRepository' => ['privates', 'App\\Repository\\PaysRepository', 'getPaysRepositoryService', true],
            'saisonRepository' => ['privates', 'App\\Repository\\SaisonRepository', 'getSaisonRepositoryService', true],
            'voyageRepository' => ['privates', 'App\\Repository\\VoyageRepository', 'getVoyageRepositoryService', true],
        ], [
            'activiteRepository' => 'App\\Repository\\ActiviteRepository',
            'favorieRepository' => 'App\\Repository\\FavorieRepository',
            'paginator' => '?',
            'pays' => 'App\\Entity\\Pays',
            'paysRepository' => 'App\\Repository\\PaysRepository',
            'saisonRepository' => 'App\\Repository\\SaisonRepository',
            'voyageRepository' => 'App\\Repository\\VoyageRepository',
        ]);
    }
}
