<?php

namespace ContainerPbWxSbT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInfoPratiqueService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.sTYWlMk.App\Entity\InfoPratique' shared service.
     *
     * @return \App\Entity\InfoPratique
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.sTYWlMk": it references class "App\\Entity\\InfoPratique" but no such service exists.');
    }
}
