<?php

namespace ContainerP7U6ZBZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5GP_VBNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5GP.vBN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5GP.vBN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'villeRepository' => ['privates', 'App\\Repository\\VilleRepository', 'getVilleRepositoryService', true],
        ], [
            'villeRepository' => 'App\\Repository\\VilleRepository',
        ]);
    }
}
