<?php

namespace ContainerP7U6ZBZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4ha6CvvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4ha6Cvv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4ha6Cvv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'PaysRepository' => ['privates', 'App\\Repository\\PaysRepository', 'getPaysRepositoryService', true],
            'SaisonRepository' => ['privates', 'App\\Repository\\SaisonRepository', 'getSaisonRepositoryService', true],
            'activiteRepository' => ['privates', 'App\\Repository\\ActiviteRepository', 'getActiviteRepositoryService', true],
            'voyage' => ['privates', '.errored..service_locator.4ha6Cvv.App\\Entity\\Voyage', NULL, 'Cannot autowire service ".service_locator.4ha6Cvv": it references class "App\\Entity\\Voyage" but no such service exists.'],
            'voyageRepository' => ['privates', 'App\\Repository\\VoyageRepository', 'getVoyageRepositoryService', true],
        ], [
            'PaysRepository' => 'App\\Repository\\PaysRepository',
            'SaisonRepository' => 'App\\Repository\\SaisonRepository',
            'activiteRepository' => 'App\\Repository\\ActiviteRepository',
            'voyage' => 'App\\Entity\\Voyage',
            'voyageRepository' => 'App\\Repository\\VoyageRepository',
        ]);
    }
}
