<?php

namespace ContainerP7U6ZBZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPays2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6gJ4TUo.App\Entity\Pays' shared service.
     *
     * @return \App\Entity\Pays
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.6gJ4TUo": it references class "App\\Entity\\Pays" but no such service exists.');
    }
}
