<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP7U6ZBZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP7U6ZBZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP7U6ZBZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP7U6ZBZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP7U6ZBZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'P7U6ZBZ',
    'container.build_id' => 'fe27ddd3',
    'container.build_time' => 1634329770,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP7U6ZBZ');
