<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4xmNZFA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4xmNZFA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4xmNZFA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4xmNZFA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4xmNZFA\App_KernelDevDebugContainer([
    'container.build_hash' => '4xmNZFA',
    'container.build_id' => 'e0b25fba',
    'container.build_time' => 1634329963,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4xmNZFA');
