<?php

namespace Container4xmNZFA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IjEdsanService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IjEdsan' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IjEdsan'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'PaysRepository' => ['privates', 'App\\Repository\\PaysRepository', 'getPaysRepositoryService', true],
            'SaisonRepository' => ['privates', 'App\\Repository\\SaisonRepository', 'getSaisonRepositoryService', true],
            'activiteRepository' => ['privates', 'App\\Repository\\ActiviteRepository', 'getActiviteRepositoryService', true],
            'favorieRepository' => ['privates', 'App\\Repository\\FavorieRepository', 'getFavorieRepositoryService', true],
            'voyage' => ['privates', '.errored..service_locator.IjEdsan.App\\Entity\\Voyage', NULL, 'Cannot autowire service ".service_locator.IjEdsan": it references class "App\\Entity\\Voyage" but no such service exists.'],
        ], [
            'PaysRepository' => 'App\\Repository\\PaysRepository',
            'SaisonRepository' => 'App\\Repository\\SaisonRepository',
            'activiteRepository' => 'App\\Repository\\ActiviteRepository',
            'favorieRepository' => 'App\\Repository\\FavorieRepository',
            'voyage' => 'App\\Entity\\Voyage',
        ]);
    }
}
