<?php

namespace Container4xmNZFA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UtK6R7IService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.utK6R7I' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.utK6R7I'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'saison' => ['privates', '.errored..service_locator.utK6R7I.App\\Entity\\Saison', NULL, 'Cannot autowire service ".service_locator.utK6R7I": it references class "App\\Entity\\Saison" but no such service exists.'],
        ], [
            'saison' => 'App\\Entity\\Saison',
        ]);
    }
}
