<?php

namespace Container4xmNZFA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G6LBObnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G6LBObn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.G6LBObn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'payement' => ['privates', 'App\\Services\\Payement', 'getPayementService', true],
            'voyageRepository' => ['privates', 'App\\Repository\\VoyageRepository', 'getVoyageRepositoryService', true],
        ], [
            'payement' => 'App\\Services\\Payement',
            'voyageRepository' => 'App\\Repository\\VoyageRepository',
        ]);
    }
}
