<?php

namespace Container4xmNZFA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdresseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.9Pc_zBs.App\Entity\Adresse' shared service.
     *
     * @return \App\Entity\Adresse
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.9Pc_zBs": it references class "App\\Entity\\Adresse" but no such service exists.');
    }
}
