<?php

namespace Container4xmNZFA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSaison2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.utK6R7I.App\Entity\Saison' shared service.
     *
     * @return \App\Entity\Saison
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.utK6R7I": it references class "App\\Entity\\Saison" but no such service exists.');
    }
}
