<?php

namespace Container4xmNZFA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTarifService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.lDH8CxR.App\Entity\Tarif' shared service.
     *
     * @return \App\Entity\Tarif
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.lDH8CxR": it references class "App\\Entity\\Tarif" but no such service exists.');
    }
}
